package com.basics.threads;

public class ResultTask extends Thread{
    @Override
    public void run(){
        System.out.println("Result Generated by: " + Thread.currentThread().getName());
    }

    public static void main(String[] args) {
        ResultTask t1= new ResultTask();
        t1.run(); // ❌ No new thread created
        t1.start(); // ✅ New Thread - Thread-0 is created
    }
}

